# Generated by Django 4.1.13 on 2024-05-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
