# Generated by Django 4.1.13 on 2024-05-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_hotel_review_user_delete_booking_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='updated_at',
        ),
    ]
