# Generated by Django 4.1.13 on 2024-05-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_hotel_created_at_remove_hotel_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Logger',
        ),
    ]
